# Generated by Django 4.1.5 on 2023-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_remove_contact_created_at_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('event', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('venue', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('budget', models.BigIntegerField()),
                ('catering', models.BooleanField()),
                ('audioVisual', models.BooleanField()),
                ('Photography', models.BooleanField()),
                ('videography', models.BooleanField()),
                ('decorations', models.BooleanField()),
                ('other', models.TextField(max_length=2000)),
            ],
        ),
    ]
