# Generated by Django 4.1.5 on 2023-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_eventbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='Photography',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='audioVisual',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='catering',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='decorations',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='videography',
            field=models.CharField(max_length=10),
        ),
    ]
