# Generated by Django 4.1.5 on 2023-04-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0007_contact_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_read',
            new_name='read',
        ),
    ]
