# Generated by Django 4.1.5 on 2023-04-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0008_rename_is_read_contact_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='read',
            new_name='is_read',
        ),
    ]
