# Generated by Django 4.1.5 on 2023-04-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0009_rename_read_contact_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='is_reads',
            field=models.BooleanField(default=False),
        ),
    ]
