# Generated by Django 4.1.5 on 2023-04-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0010_eventbooking_is_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('pass1', models.CharField(max_length=100)),
                ('pass2', models.CharField(max_length=100)),
            ],
        ),
    ]
