# Generated by Django 4.1.5 on 2023-04-02 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0011_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
    ]
