# Generated by Django 4.1.5 on 2023-05-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0014_admin_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='usertype',
            field=models.CharField(max_length=30),
        ),
    ]
